declare type CorePropsT = {
	onClick?: Function,
	onContextMenu?: Function,
	onDoubleClick?: Function,
	onDrag?: Function,
	onDragEnd?: Function,
	onDragEnter?: Function,
	onDragExit?: Function,
	onDragLeave?: Function,
	onDragOver?: Function,
	onDragStart?: Function,
	onDrop?: Function,
	onMouseDown?: Function,
	onMouseEnter?: Function,
	onMouseLeave?: Function,
	onMouseMove?: Function,
	onMouseOut?: Function,
	onMouseOver?: Function,
	onMouseUp?: Function,
	onKeyDown?: Function,
	onKeyPress?: Function,
	onKeyUp?: Function,
	onCopy?: Function,
	onCut?: Function,
	onPaste?: Function,
};
